    <script src="<?= site_base_url() ?>/admin/plugins/jquery/jquery.min.js"></script>
    <script src="<?= site_base_url() ?>/admin/plugins/bootstrap/js/bootstrap.js"></script>
    <script src="<?= site_base_url() ?>/admin/plugins/bootstrap-select/js/bootstrap-select.js"></script>
    <script src="<?= site_base_url() ?>/admin/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
    <script src="<?= site_base_url() ?>/admin/plugins/node-waves/waves.js"></script>
    <script src="<?= site_base_url() ?>/admin/plugins/jquery-countto/jquery.countTo.js"></script>
    <script src="<?= site_base_url() ?>/admin/plugins/raphael/raphael.min.js"></script>
    <script src="<?= site_base_url() ?>/admin/plugins/morrisjs/morris.js"></script>
    <script src="<?= site_base_url() ?>admin/plugins/chartjs/Chart.bundle.js"></script>
    <script src="<?= site_base_url() ?>/admin/plugins/flot-charts/jquery.flot.js"></script>
    <script src="<?= site_base_url() ?>/admin/plugins/flot-charts/jquery.flot.resize.js"></script>
    <script src="<?= site_base_url() ?>/admin/plugins/flot-charts/jquery.flot.pie.js"></script>
    <script src="<?= site_base_url() ?>/admin/plugins/flot-charts/jquery.flot.categories.js"></script>
    <script src="<?= site_base_url() ?>/admin/plugins/flot-charts/jquery.flot.time.js"></script>
    <script src="<?= site_base_url() ?>/admin/plugins/jquery-sparkline/jquery.sparkline.js"></script>    
    <script src="<?= site_base_url() ?>/admin/js/admin.js"></script>
    <script src="<?= site_base_url() ?>/admin/js/pages/index.js"></script>